springdoc:
  swagger-ui:
    url: /template-api-yml-configuration/template-api.yml
auth:
  token:
    jwkUrl: https://virava-keycloak.thepineslab.net/auth/realms/crc-test/protocol/openid-connect/certs
    emailPath: email
    usernamePath: preferred_username
    rolesPath: resource_access.crc-test.roles
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: stanislav
    password: test123
    virtual-host: plex_virtual_host
  datasource:
    jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databaseName=my-mssql;encrypt=true;trustServerCertificate=true;
    username: sa
    password: P@ssw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServerDialect

second-datasource:
  datasource:
    jdbc-url: jdbc:sqlite:/Users/stanislavarabov/Downloads/5.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      show-sql: true
      database-platform: org.hibernate.community.dialect.SQLiteDialect